import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { TimerSettingsProvider } from "./components/Timer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TimerSettingsProvider >
          {children}
        </TimerSettingsProvider>
      </body>
    </html>
  );
}
